kind: pipeline
type: docker
name: Unity builds

environment:
    BUILD_TARGET: StandaloneWindows64
    BUILD_NAME: Windows
    NAS_BUILD_DIRECTORY: Builds/nas
    ITCH_BUILD_DIRECTORY: Builds/itch

steps:
- name: create unity activation file
  image: gableroux/unity3d:2019.3.0f6-windows
  environment:
    UNITY_USERNAME: philipullersted@gmail.com
    UNITY_PASSWORD: 20572057
    UNITY_ACTIVATION_FILE: ./unity3d.alf
  commands:
  - chmod +x ./ci/get_activation_file.sh
  - ./ci/get_activation_file.sh

- name: create unity license file
  image: gableroux/unity3d-activator:v1.0.1
  environment:
    UNITY_USERNAME: philipullersted@gmail.com
    UNITY_PASSWORD: 20572057
    UNITY_ACTIVATION_FILE: ./unity3d.alf
    UNITY_LICENSE_FILE: ./Unity_lic.ulf
  commands:
  - unity3d-activator

- name: upload debug images
  image: cschlosser/drone-ftps
  environment:
    PLUGIN_HOSTNAME: 192.168.1.184:21
    FTP_USERNAME:
      from_secret: ftp_username
    FTP_PASSWORD:
      from_secret: ftp_password
    PLUGIN_DEST_DIR: /sync/data/ci/debug_images
    PLUGIN_SRC_DIR: /debug_images/
    PLUGIN_SECURE: true
    PLUGIN_VERIFY: false
  when:
    status:
      - failure

- name: building windows build
  image: gableroux/unity3d:2019.3.0f6-windows
  commands:
  - chmod +x ./ci/before_script.sh
  - ./ci/before_script.sh
  - chmod +x ./ci/build.sh
  - ./ci/build.sh
  - echo $Test

- name: after windows build
  image: eamonwoortman/alpine-curl-zip
  environment:
    BUILD_PATH: Builds/StandaloneWindows64/
  commands:
  - chmod +x ./ci/after_build.sh
  - ./ci/after_build.sh

- name: upload windows build to nas
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
    RSYNC_USER:
      from_secret: rsync_user
  settings:
    hosts:
      - 100.89.231.101
    source: Builds/nas/
    target: /mnt/storage/public/game_builds/
    recursive: true

- name: upload build to itch
  image: dosowisko/butler
  environment:
    BUTLER_API_KEY:
      from_secret: butler_api_key
  commands:
  - chmod +x ./ci/upload_itch.sh
  - ./ci/upload_itch.sh

- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id: 701545979668594759
    webhook_token: 8wyFjGo-VcFjOe_sA77dsv9s0tZcwPXeFp6ZIrdHXfeyuKmfH6pqrH-7PIf00R8obl_v
    message: >
      {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}