kind: pipeline
type: docker
name: Unity builds

environment:
  WINDOWS_BUILD_DIRECTORY: CIBuilds/Windows
  WEBGL_BUILD_DIRECTORY: Builds/WebGL

steps:
- name: create unity activation file
  image: gableroux/unity3d:2019.4.11f1-windows
  environment:
    UNITY_USERNAME: philipullersted@gmail.com
    UNITY_PASSWORD: 20572057
    UNITY_ACTIVATION_FILE: ./unity3d.alf
  commands:
  - echo $PLUGIN_DEST_DIR
  - chmod +x ./ci/get_activation_file.sh
  - ./ci/get_activation_file.sh

- name: create unity license file
  image: gableroux/unity3d-activator:v1.0.1
  environment:
    UNITY_USERNAME: philipullersted@gmail.com
    UNITY_PASSWORD: 20572057
    UNITY_ACTIVATION_FILE: ./unity3d.alf
    UNITY_LICENSE_FILE: ./Unity_lic.ulf
  commands:
  - unity3d-activator

- name: building windows build
  image: gableroux/unity3d:2019.4.11f1-windows
  environment:
    BUILD_TARGET: StandaloneWindows64
    BUILD_NAME: Windows
  commands:
  - chmod +x ./ci/before_script.sh
  - ./ci/before_script.sh
  - chmod +x ./ci/build.sh
  - ./ci/build.sh

- name: after windows build
  image: eamonwoortman/alpine-curl-zip
  environment:
    BUILD_PATH: Builds/StandaloneWindows64
    BUILD_NAME: Windows
  commands:
  - chmod +x ./ci/after_windows_build.sh
  - ./ci/after_windows_build.sh

- name: upload windows build to itch
  image: dosowisko/butler
  environment:
    BUTLER_API_KEY:
      from_secret: butler_api_key
    BUILD_NAME: Windows
  commands:
  - export ITCH_BUILD_DIRECTORY=$WINDOWS_BUILD_DIRECTORY
  - chmod +x ./ci/upload_itch.sh
  - ./ci/upload_itch.sh

- name: upload windows build to nas
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
    RSYNC_USER:
      from_secret: rsync_user
    BUILD_NAME: Windows
  settings:
    hosts: 192.168.1.166
    recursive: true
  prescript:
  - mkdir -p $PLUGIN_TARGET
  commands:
  - export ZIP_FILE_NAME="$DRONE_BUILD_NUMBER-$BUILD_NAME-$DRONE_COMMIT_AUTHOR_NAME-$DRONE_COMMIT_MESSAGE"
    # Remove invalid characters in NAS_UPLOAD_PATH_NAME
  - ZIP_FILE_NAME=`echo $ZIP_FILE_NAME | sed 's/[^A-Za-z0-9._[:space:]-]//g'`
  - mv "$(pwd)/$WINDOWS_BUILD_DIRECTORY/$BUILD_NAME.zip" "$(pwd)/$WINDOWS_BUILD_DIRECTORY/$ZIP_FILE_NAME.zip"
  - export PLUGIN_TARGET="/mnt/storage/public/game_builds/$DRONE_REPO_NAME/Windows/"
  - export PLUGIN_SOURCE="$(pwd)/$WINDOWS_BUILD_DIRECTORY/"
  - /usr/local/upload.sh

- name: building webgl build
  image: gableroux/unity3d:2019.4.11f1-webgl
  environment:
    BUILD_TARGET: WebGL
    BUILD_NAME: WebGL
  commands:
  - chmod +x ./ci/before_script.sh
  - ./ci/before_script.sh
  - chmod +x ./ci/build.sh
  - ./ci/build.sh

- name: upload webgl build to itch
  image: dosowisko/butler
  environment:
    BUTLER_API_KEY:
      from_secret: butler_api_key
    BUILD_NAME: WebGL
  commands:
  - export ITCH_BUILD_DIRECTORY=$(pwd)/$WEBGL_BUILD_DIRECTORY
  - chmod +x ./ci/upload_itch.sh
  - ./ci/upload_itch.sh

- name: upload webgl build to nas
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
    RSYNC_USER:
      from_secret: rsync_user
    BUILD_NAME: Windows
  settings:
    hosts: 192.168.1.166
    recursive: true
  prescript:
  - mkdir -p $PLUGIN_TARGET
  commands:
  - export NAS_UPLOAD_PATH_NAME='${DRONE_BUILD_NUMBER}-${BUILD_NAME}-${DRONE_COMMIT_AUTHOR_NAME}-${DRONE_COMMIT_MESSAGE}'
    # Remove invalid characters in NAS_UPLOAD_PATH_NAME
  - NAS_UPLOAD_PATH_NAME=`echo ${NAS_UPLOAD_PATH_NAME} | sed 's/[^A-Za-z0-9._-]//g'`
  - export PLUGIN_TARGET="/mnt/storage/public/game_builds/$DRONE_REPO_NAME/WebGl/$NAS_UPLOAD_PATH_NAME/"
  - export PLUGIN_SOURCE="$(pwd)/$WEBGL_BUILD_DIRECTORY/"
  - /usr/local/upload.sh

- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id: 701545979668594759
    webhook_token: 8wyFjGo-VcFjOe_sA77dsv9s0tZcwPXeFp6ZIrdHXfeyuKmfH6pqrH-7PIf00R8obl_v
    message: >
      {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
  when:
    status:
    - failure
    - success
